# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Ladmcoluv
                                 A QGIS plugin
 Plugin de Qgis para la evaluación de calidad en el proceso de captura y mantenimiento de datos conformes con el modelo LADM-COL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-06
        copyright            : (C) 2023 by Escuela de Ingenieria Civil y Geomática - Universidad del Valle

        email                : areageomatica@correounivalle.edu.co 
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Ladmcoluv class from file Ladmcoluv.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ladm_col_uv import Ladmcoluv
    return Ladmcoluv(iface)
